Ensure only .data and .text ends up in hex file
With gcc8, the .noinit section is marked as "CONTENTS, ALLOC, LOAD, DATA", compared to just
"ALLOCC" in previous versions. This causes avr-objcopy to include it in default output list,
which then fails to flash since it is out of range:
  ERROR: address 0x8000db out of range at line 320 of ../image.hex